on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        #python-version: [2.7, 3.5, 3.6, 3.7]
        #python-version: [3.5, 3.6, 3.7, 3.x]
        python-version: [3.x]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: lint with black
      continue-on-error: true
      run: |
        pip install black
        black --check .
    - name: Lint with flake8
      continue-on-error: true
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      continue-on-error: true
      run: |
        pip install pytest
        pytest
    - run: |
        python test_code/jsonParse-history-py3.py Galaxy-History-BCO-Test/
    - env:
        GALAXY_REPO: https://github.com/galaxyproject/galaxy
        GALAXY_RELEASE: release_19.05
        PLANEMO_CONDA_PREFIX: "$HOME/conda"
        #JAVA_HOME
      # planemo 0.62.1 'planemo conda_init' appeared to fail without '--conda_prefix'
      # because $HOME was not expanded:
      # '$HOME/conda/bin/conda' install -y --override-channels --channel iuc --channel conda-forge --channel bioconda --channel defaults conda=4.3.33 conda-build=2.1.18
      # FileNotFoundError: [Errno 2] No such file or directory: '$HOME/conda/bin/conda'
      run: |
        pip install planemo
        #planemo conda_init --conda_prefix=$HOME/conda --conda_exec=$HOME/conda/bin/conda
        planemo conda_init --conda_prefix=$HOME/conda
        export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
        planemo lint
        planemo test

#--conda_prefix DIRECTORY        Conda prefix to use for conda dependency commands.
#--conda_exec FILE               Location of conda executable.

